(* Convey Defines *)
(* {$Include ConveyVer.inc} *)

{$Define FullDisableAllocator}
{$Define DUGO}

{$IfDef VER150}
{$Define CNVD7}
{$Define CNVD7H}
{$EndIf}

{$IfDef VER180}
{$Define CNVD10}
{$Define CNVD7H}
{$Define CNVD10H}
{$EndIf}

{$IfDef VER185}
{$Define CNVD10}
{$Define CNVD11}
{$Define CNVD7H}
{$Define CNVD10H}
{$Define CNVD11H}
{$EndIf}

{$IfDef VER200}
{$Define CNVD12}
{$Define CNVD7H}
{$Define CNVD10H}
{$Define CNVD11H}
{$Define CNVD12H}
{$EndIf}

{$IfDef VER210}
{$Define CNVD13}
{$Define CNVD7H}
{$Define CNVD10H}
{$Define CNVD11H}
{$Define CNVD12H}
{$Define CNVD13H}
{$EndIf}

{$IfDef VER220}
{$Define CNVD14}
{$Define CNVD7H}
{$Define CNVD10H}
{$Define CNVD11H}
{$Define CNVD12H}
{$Define CNVD13H}
{$Define CNVD14H}
{$EndIf}

{$IfDef VER230}
{$Define CNVD15}
{$Define CNVD7H}
{$Define CNVD10H}
{$Define CNVD11H}
{$Define CNVD12H}
{$Define CNVD13H}
{$Define CNVD14H}
{$Define CNVD15H}
{$EndIf}

{$IfDef VER240}
{$Define CNVD16}
{$Define CNVD7H}
{$Define CNVD10H}
{$Define CNVD11H}
{$Define CNVD12H}
{$Define CNVD13H}
{$Define CNVD14H}
{$Define CNVD15H}
{$Define CNVD16H}
{$EndIf}

{$IfDef VER250}
{$Define CNVD16}
{$Define CNVD7H}
{$Define CNVD10H}
{$Define CNVD11H}
{$Define CNVD12H}
{$Define CNVD13H}
{$Define CNVD14H}
{$Define CNVD15H}
{$Define CNVD16H}
{$Define CNVD17H}
{$EndIf}

{$IfDef CNVD10H}
{$Define USEVCLDESIGNER}
{$Define PRODELPHI}
{$EndIF}

{
Tool - Version - Define
VER210 - Delphi 2010
VER220 - Delphi XE
VER230 - Delphi XE2
VER240 - Delphi XE3
VER250 - Delphi XE4

CodeGear Delphi 2009  12.0  VER200
CodeGear C++ Builder 2009  12.0  VER200
CodeGear Delphi 2007 for .NET  11.0  VER190
CodeGear Delphi 2007 for Win32  11.0  VER180 and VER185
Borland Developer Studio 2006  10.0  VER180
Borland Delphi 2005  9.0  VER170
Borland Delphi 8 for .NET  8.0  VER160 *
C++BuilderX   ?   ?
Borland C#Builder  1.0  VER160 *
Borland Delphi 7  7.0  VER150
Borland Kylix 3  3.0  VER140 **
Borland C++Builder 6   ?  VER140 **
Borland Kylix 2  2.0  VER140 **
Borland Delphi 6  6.0  VER140 **
Borland Kylix  1.0  VER140 **
Borland C++Builder 5   ?  VER130 ***
Borland Delphi 5  5.0  VER130 ***
Borland C++Builder 4   ?  VER125
Borland Delphi 4  4.0  VER120
Borland C++Builder 3   ?  VER110 ****
Borland Delphi 3  3.0  VER100
Borland C++ 5   ?   ?
Borland C++Builder 1   ?  VER93
Borland Delphi 2  2.0  VER90
Borland C++ 4.5   ?   ?
Borland Delphi  1.0  VER80
Borland C++ 4   ?   ?
Borland Pascal 7  7.0  VER70
Borland C++ 3.1   ?   ?
Turbo Pascal for Windows 1.5  1.5  VER70
Turbo C++ for DOS 3   ?   ?
Borland C++ 3   ?   ?
Turbo C++ for Windows 3 (Win16)   ?   ?
Turbo Pascal for Windows 1.0  1.0   ???
Borland C++ 2   ?   ?
Turbo Pascal 6  6.0  VER60
Turbo C++ for DOS   ?   ?
Turbo C for DOS 2   ?   ?
Turbo Pascal 5.5  5.5  VER55
Turbo C for DOS 1.5   ?   ?
Turbo Pascal 5  5.0  VER50
Turbo Pascal 4  4.0  VER40
Turbo C for DOS   ?   ?
Turbo Pascal 3  3.0   ???
Turbo Pascal 2  2.0   ???
Turbo Pascal 1  1.0   ???

}